### ISSUE TITLE
error during installation: sail npm install

### ISSUE THREAD

**Issue by frank-fft** [artwork-software/artwork#166]
Hi, 
i get an error during installation at point 3:

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /var/www/html/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/var/www/html/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/var/www/html/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/var/www/html/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by Muelle96** [comment]
Hi,
it seems that you are not running the command as an administrator. try running the command( the terminal window) as an administrator. It seems that you dont have the permission to use the npm install command. If you have further problems let me know.
