### ISSUE TITLE
Segmentation fault while trying to start the frontend

### ISSUE THREAD

**Issue by n4g0r** [artwork-software/artwork#351]
Hi,
for evaluating Artwork I'm trying to set it up on macOS via Docker. I'm getting through the process smoothly until i run "sail npm run dev". I'm posting multiple executions below as the result is varying a bit but overall no process is happening. There are all 4 containers running, the database created succesfully and the queue is running. The sourcecode is freshly from git.
Any ideas?
Kind regards

```
fg@Frederics-MacBook-Air artwork % sail npm run dev

> dev
> npm run development


> development
> mix


● Mix █████████████████████████  (0%)  
 

Segmentation fault
fg@Frederics-MacBook-Air artwork % sail npm run dev 

> dev
> npm run development


> development
> mix


● Mix █████████████████████████ building (10%) 0/2 entries 2/2 dependencies 0/
2 modules 2 active 
 css-loader › postcss-loader › resources/css/app.css

Segmentation fault
fg@Frederics-MacBook-Air artwork % sail npm run dev 

> dev
> npm run development


> development
> mix


● Mix █████████████████████████ building (10%) 0/2 entries 2/2 dependencies 0/
2 modules 2 active 
 babel-loader › resources/js/app.js

Segmentation fault
fg@Frederics-MacBook-Air artwork % sail npm run dev 

> dev
> npm run development


> development
> mix


● Mix █████████████████████████ building (10%) 0/2 entries 2/2 dependencies 0/
2 modules 1 active 
 css-loader › postcss-loader › resources/css/app.css

Segmentation fault
fg@Frederics-MacBook-Air artwork % sail npm run dev 

> dev
> npm run development


> development
> mix


● Mix █████████████████████████  (0%)  
 

Segmentation fault
```

**Comment by Muelle96** [comment]
Hi,

we just tried to install artwork on a new mac and it went through without problems. 

Regarding your error i suggest you 
1.either delete your node_modules with the command "rm -rf "in your node_modules folder and then install them again with "sail npm install"
or
2. you try to install it again completely new

I am sorry that i cant provide an clear solution, but we cant reproduce your error here, if you still have issues feel free to contact us again.
