### ISSUE TITLE
Automated Deployment of Releases and Nightlies to Dockerhub

### ISSUE THREAD

**Issue by dheid** [artwork-software/artwork#392]
Dear artwork Team,

Firstly, I would like to express my gratitude for developing such a valuable tool for the arts community.

To further enhance the accessibility and ease of deployment for users, I would like to request the implementation of automated deployment of both releases and nightly builds to the official Dockerhub repository.

Automating the deployment process to Dockerhub would streamline the distribution of artwork, making it more convenient for users to access and utilize the software across various environments.

I believe this enhancement aligns with the open and collaborative spirit of artwork, empowering users to readily deploy and utilize the latest versions of the software.

Looking forward to your consideration of this request.

Best regards,
Daniel

**Comment by B3nWil** [comment]
Hi Daniel,

our Dockerhub integration is ready now. All future updates on the dev, staging and main branches will generate an image found on https://hub.docker.com/repository/docker/muelle96/artwork/general

I hope that's helpful and supports a quicker distribution.

Regards
