### ISSUE TITLE
Dropdown Menü

### ISSUE THREAD

**Issue by FabianStemmer** [artwork-software/artwork#547]
Moin,

wenn man in den Komponenteneinstellungen ein neues Dropdown Menü erzeugt (in meinem Fall 'Ansprechpartner Technik') mit vier Namen drin und das in den Tabeinstellungen in einen neuen Tab schiebt (in meinem Fall 'Ansprechpartner') und dann in einem Projekt den Namen aus dem Dropdown Menü ändern will, bekommt man folgenden Fehler:

Undefined array key "data"

wenn man nicht in der /artwork/Modules/ProjectTab/Models/ProjectComponentValue.php

Zeile 29 von

return strip_tags($this->data['text']);

in 

return strip_tags($this->data['text'] ?? '');

ändert.

Beste Grüße,
Fabian

**Comment by timodeeken** [comment]
Guten Tag, dieser Fehler wurde bereits von uns behoben. 
Gerne einmal prüfen ob sie die neueste Version von Artwork haben. 

Hier einmal der Code aus der ProjectComponentValue:

```
public function getTextWithoutHtmlAttribute(): string
{
    // check if the data is an array and has a key 'text'
    if (!is_array($this->data) || !array_key_exists('text', $this->data)) {
        return '';
    }
    return strip_tags($this->data['text']);
}
```
