### ISSUE TITLE
Installation fails: ubuntu-install.sh not installing Node.js

### ISSUE THREAD

**Issue by guischdi** [artwork-software/artwork#598]
Hi,

when using the `ubuntu-install.sh` script on a fresh Ubuntu 22.04, node/npm is not being installed (as it should be according to the README). This can be seen at various outputs of:
```shell
sudo: npm: command not found
sudo: npm: command not found
sudo: pm2: command not found
```
at the end and in between other logging while the script is running. (see [artwork-install.log](https://github.com/user-attachments/files/16400307/artwork-install.log) attached)

The script terminates with a zero exit code, so I tend to ignore those logs. (Please provide some documentation how to check if an installation was successful!)

But: After adjusting the `.env` variable `APP_URL` (as stated in the README), when navigating the browser to the that url, the browser redirects to `/setup`, which then responds with a `500` HTTP code. The [laravel.log](https://github.com/user-attachments/files/16400313/laravel.log) shows that Vite is not installed (probably because node/npm ist not installed):
```shell
[2024-07-27 15:06:38] production.ERROR: Vite manifest not found at: /var/www/html/public/build/manifest.json {"view":{"view":"/var/www/html/resources/views/app.blade.php","data":[]},"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Vite manifest not found at: /var/www/html/public/build/manifest.json at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php:728)
```

**Comment by updatedData** [comment]
Hello, thanks for bringing this to our attention. As you might know Artwork is a very fast growing software. Recently we had some breaking changes due to refactoring and technology switches. One of those for example was the switch from webpack to vite.

Specific issue with the install script has been adressed in this https://github.com/artwork-software/artwork/pull/603 pull request updates for the issues are currently in the making and we hope to ship them later this day.

Kind regards

**Comment by guischdi** [comment]
Thanks for adressing the issue. I will test it soon and let you know if it works for me.

**Comment by guischdi** [comment]
The script shows the following warning (at least when executed with the shortcut `sudo curl -fsSL <url> | sh` command):
```shell
sh: 86: cannot create /var/www/html/.env: Permission denied
```

But the `.env` file is present after the installation and the application ist properly running (except for missing image files).
