### ISSUE TITLE
Installation fails: docker standalone installation starting container with various errors

### ISSUE THREAD

**Issue by guischdi** [artwork-software/artwork#600]
If you use the [Docker installation Standalone](https://github.com/artwork-software/artwork#docker-installation-standalone) guide to start artwork via `docker compose`, the installation and the startup work and result in a running container, but various errors occurr:

### Some supervisord misconfiguration?
```
production.ERROR: Command "artwork:container-update" is not defined.
```
(`did you mean container-update` might be a solution at hand)

### Some Laravel misconfiguration? (actually no clue 💁)
```
production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
```

### Redis not started?
```
production.ERROR: Connection refused {"exception":"[object] (RedisException(code: 0): Connection refused at /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:159)
```

## Steps to reproduce
- use a fresh linux os (i used a fresh Ubuntu 22.04)
- [install docker](https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script)
- clone the artwork repository (i used the `dev` branch)
- rename the `.env.prod.example` file to `.env` (according to README)
- run `docker compose -f docker-compose-production.yml up -d` (according to README)
- watch the build and startup (everything looks fine)
- run `docker compose -f docker-compose-production.yml exec artwork php artisan key:generate --show` and insert the key into the `.env` variable `APP_KEY` (according to README), also add the `APP_URL`.
- restart the container (according to README) using `docker compose -f docker-compose-production.yml restart artwork`
- attempt to head your browser to the app url, you'll see a 500 | Server Error
- have a look at the [laravel.log](https://github.com/user-attachments/files/16400603/laravel.log) (get it via `docker compose -f docker-compose-production.yml exec artwork cat storage/logs/laravel.log`)

PS:
a `ps -aux` within the running container (`docker compose exec artwork ps -aux`) shows some running processes. I didn't dig deeper, which of this services are actually running properly and which are in malicious state (just frustrated all installation methods seem to fail).
```shell
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.7  33208 27128 ?        Ss   14:25   0:00 /usr/bin/python3 /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
mysql          7  0.6 10.4 1325028 392112 ?      Sl   14:25   0:09 mysqld
root           8  0.0  2.2 185740 83664 ?        S    14:25   0:00 php /var/www/html/artisan queue:work
root          10  0.0  2.2 185740 83920 ?        S    14:25   0:00 /usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80
root          11  0.1  0.2  64232 10368 ?        Sl   14:25   0:02 redis-server *:6379
root          12  0.6  2.1 656164 80352 ?        Sl   14:25   0:10 soketi-server
root          47  0.0  2.0 278564 78528 ?        S    14:25   0:00 /usr/bin/php8.2 -S 0.0.0.0:80 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/../resources/server.php
root         145  0.0  0.0   7064  2944 pts/0    Rs+  14:49   0:00 ps -aux
```
Maybe that output may help.
Due to my investigations in the `supervisord.conf` (used in the Dockerfile which is built whilst the `docker compose up`) I would assume all the needed services are running. But there is no documentation on which services should be running for an artwork instance to be healthy. So, no clue, if there are some process missing in that list 🤷

**Comment by guischdi** [comment]
Additionally: don't hesitate to tell me, where more logs can be found, Laravel log is just the first one I found ;) Some advise on how to determine the health status of the instance would be awesome.

**Comment by updatedData** [comment]
Hi, the build was breaking due to the switch from webpack to vite.

Also it is enough to run `docker compose -f docker-compose-production.yml up -d` to reload the `.env` file for the container. I've fixed the image and also took the chance to update from Ubuntu 22.04 to Ubuntu 24.04.

Regarding healthstatus: the container exposes the relevant ports like 3306 for database or 80 for http. You can test against those, all services also log into stdout and stderr. Meaning you can find the application logs in your docker logs.

Kind regards

**Comment by guischdi** [comment]
Hi,

> the build was breaking

... means it is not breaking any more? If so, I will test it in the next days.

Also, health to me doesn't simply mean: 'ports are open'. Port 80 was open even with a breaking build. It was a 500 off course, but as stated, some advise on how to check if everything is up would be great. Maybe a simple mysql query to be sent to the mysql instance and a health endpoint in the application which responds with some basic information about the status (connection to db, redis, meilisearch, ...).

**Comment by updatedData** [comment]
Hi Guischdi, I did not mean to say "ports are open and thats healthy", I meant that you can build your own healthchecks, either from the `docker-compose`-files or from an outside system which monitors your stack. 

Providing healthchecks is currently not on the roadmap of the project. 

For example a simple healthcheck for the db in a docker-compose file would be:

```
 healthcheck:
   test:
     - CMD
     - mysqladmin
     - ping
     - '-p${DB_PASSWORD}'
   retries: 3
  timeout: 5s
```

If you have any good ideas, please feel free to contribute since Artwork is open source and helping hands are always welcome.

Kind Regards
