### ISSUE TITLE
Installation fails: Laravel Sail Docker installation fails at dependencies

### ISSUE THREAD

**Issue by guischdi** [artwork-software/artwork#601]
While performing `composer install --ignore-platform-reqs` (according to README) I get the following error:
```
  - Syncing phpstan/phpstan (1.11.5) into cache
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

In Process.php line 1205:
                                                                                                                                                                                               
  The process "git clone --mirror -- 'https://github.com/phpstan/phpstan.git' '/home/mail_/.cache/composer/vcs/https---github.com-phpstan-phpstan.git/'" exceeded the timeout of 300 seconds.
```
  
 ### Steps to reproduce
- use a fresh linux os (i used a fresh Ubuntu 22.04)
- [install docker](https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script)
- clone the artwork repository (`git clone https://github.com/artwork-software/artwork.git`)
- rename the .env.example file to .env (according to README)
- run `composer install --ignore-platform-reqs` (according to README)

I also tried manually downloading the repository at which the process stoped, without success (btw. it's 5GB, `wtf.php`):
```
git clone --mirror -- 'https://github.com/phpstan/phpstan.git' '/home/mail_/.cache/composer/vcs/https---github.com-phpstan-phpstan.git/'
Cloning into bare repository '/home/mail_/.cache/composer/vcs/https---github.com-phpstan-phpstan.git'...
remote: Enumerating objects: 100705, done.
remote: Counting objects: 100% (2686/2686), done.
remote: Compressing objects: 100% (1349/1349), done.
remote: Total 100705 (delta 1451), reused 2483 (delta 1337), pack-reused 98019
Receiving objects: 100% (100705/100705), 4.92 GiB | 28.61 MiB/s, done.
Resolving deltas: 100% (70370/70370), done.
error: unable to write file /home/mail_/.cache/composer/vcs/https---github.com-phpstan-phpstan.git/objects/pack/pack-39d7f4d761ffa10574abf5bb052bbb75068c1f0b.pack: No such file or directory
fatal: cannot store pack file
fatal: index-pack failed
```

Conclusion:
None of the three installation methods mentioned in the README actually works. I'm a somewhat experienced devOp, but failed with all of those methods. At least one of them should maybe work properly for this software to be called open source. Took me a whole 5 hours only to conclude that I won't have a running artwork instance for another while and I need the developers to setup an instance.

**Comment by updatedData** [comment]
Hi sorry to hear that. It seems there might be something wrong with your system or the dependency manager (Composer) had some issues. The latter is outside of our power.

Please refrain from trying to manually resolve dependencies without Composer.

I have tried it and it was working for me. Maybe you could give it another go?
