### ISSUE TITLE
Bunch of Bugs

### ISSUE THREAD

**Issue by guischdi** [artwork-software/artwork#662]
Collection of all the bugs that came up during the testing of artwork and the development of a migration from KulturKlick to artwork. Some just unattractive, some very serious. In german due to lack of time.

## Generell

* [x] Der Aufruf mancher Seiten führt zu einem Aufwand von O(n²) oder sogar O(nⁿ). Deshalb musste der Import insbesondere folgender Resourcen massiv eingeschränkt werden:
  * [x] Abwesenheiten (vacations), legt User-Seite (\`/users/\<id\>/shiftplan\`) lahm, ab ca. 1k bis 2k vacations
  * [x] Schichten (shifts) legt User-Liste lahm, ab ca. 1k bis 3k shifts
  * [x] Inventarzuordnung legt Bestandsdisposition (\`/inventory-management/scheduling\`) lahm, ab ca. 3k bis 4k craft_inventory_item_events

    Das laden dieser Seiten ist entweder ins RAM- oder Timelimit für PHP-Execution gelaufen. (Und wir haben RAM schon auf 4GB und 60s erhöht).
* [x] Jede Nacht um Mitternacht `production.ERROR: Please implement the prunable method on your model. {"exception":"[object] (LogicException(code: 0): Please implement the prunable method on your model. at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Prunable.php:41)`
* [x] Tabwechsel persistiert Tab nicht, aus dem man wegwechselt (wenn noch focus in Textfeld ist)
* [x] Bild-Upload funktioniert nicht. Wird zwar Ladebalken und Vorschau angezeigt, ist aber nicht persistent → liegt an falscher url-Zusammensetzung ([localhost](http://localhost))

  Stellt sich raus: wenn man die `.env` verändert, sollte man danach folgende Kommandos ausführen:

  ```console
  $ php /var/www/html/artisan config:clear
  $ php /var/www/html/artisan config:cache
  ```

  Auf einmal gehen auch die Logos... Also bitte so dokumentieren!

## Raumeinstellungen

- [x] Anlegen inpersistent (Tags fehlen nach reload)
- [x] UI-Statemanagement kaputt (Raum öffnen, dann anderen Raum öffnen und Tags von vorherigem sind noch sichtbar. Reload hilft.)

## Projektrolleneinstellungen

- [x] Namensänderung nicht möglich. `Ziggy error: 'project_role' parameter is required for route 'project-roles.update'`
- [x] Löschung nicht möglich `Ziggy error: 'project_role' parameter is required for route 'project-roles.destroy'.`

## Projekteinstellungen

- [x] 500 auf Projektseite, wenn man Budget-Tab aus Tabeinstellungen entfernt. Hinzufügen eines Tabs mit den Namen Budget hilft, ist nur unnötig, wenn man nichts mit Budget machen will.
- [x] Titelkomponenten werden falsch verwendet (Titel der Komponente statt Titeltext wird angezeigt)

## Termineinstellungen

- [x] default Farbe beim Anlegen nicht weiß (wie der color picker vermuten lässt).
- [x] Farbe nicht änderbar.
- [x] Abkürzung bei Bearbeiten nicht vorausgefüllt
- [x] Abkürzung nicht änderbar

## Projektliste/Projekte

- [x] Projektgruppe nach Anlegen nicht als Projektgruppe wählbar in Projekten.
- [x] Projekte nicht wählbar bei anlegen einer Projektgruppe.
- [x] Focus Management kaputt. a) Focus in Textfeld macht keinen Cursor. b) Wechsel von einem in anderes Textfeld nicht möglich ohne UI-Krampf (Page-Reload beim blur aus dem ersten focus verhindert focus auf zweitem Textfeld)!
- [x] Projekt-Gruppen-Zugehörigkeit wird falschrum dargestellt: "gehört zu" müsste "beinhaltet" heißen. (Ist auch falschrum in der Datenbank hinterlegt)
- [x] Fehlender Link vom Projekt zur Projektgruppe. Nur textlich vermerkt.
- [x] Pagination kaputt bei Suche in Projektliste (Klick auf nächste Seite killt Suchergebnisse und verweist einfach zur nächsten Seite der ungefilterten Liste).
- [x] Weitere Rolle \> Projektleitung Checkbox wird im 'Projektteam zuweisen'-Popup nicht mehr angezeigt, wenn man sie einmal für ein User ausgewählt hat, User kann also nicht aus dieser Rolle entlassen werden
- [x] Kommentare werden mit Zeilenumbrüchen gespeichert aber ohne angezeigt
- [x] Textareas können HTML darstellen (importiert aus KulturKlick), aber nicht bearbeiten. Ergo beim Bearbeiten des Texts wird dann nur noch Plaintext gespeichert.
- [x] Vergangene Termine sind hinweislos ausgeblendet. Scheinbar "leeren" Terminfilter zurücksetzen und sie tauchen wieder auf. UX-Gold!

## Kalender

- [x] Export bitte nach Datumsfilter der Ansicht, nicht default auf heut
- [x] Export in Listenmodus leer

## Termin

- [x] Beschreibung wird nicht gespeichert (weder beim Anlegen, noch beim Editieren). Angezeigt wird's auch nicht. Super!
- [x] 13:13 ist nach 12:12 des Vortages und auch länger als 30 Minuten:
<img width="615" alt="Screenshot_2024-08-28_at_18 25 13" src="https://github.com/user-attachments/assets/5d8f5416-3e65-4cb6-b8d3-4ff18a2911d2">

## Schichtplanung

- [x] Schicht nicht änderbar (gewünschte Personenzahl, Zeitfenster), außer man löscht den ganzen Schichtplan eines Termins.
- [x] Kalenderwochen vor/zurück Buttons funktionslos.

## Bestandsdisposition

* [x] 500er, wenn mehr als \~3.500 Bestands-Zuweisungen (Nutzungen) in craft_inventory_item_events Tabelle. Log siehe 
[craft_inventory_item_events-error.log](https://github.com/user-attachments/files/16836912/craft_inventory_item_events-error.log)
* [x] Kalenderwochen vor/zurück Buttons funktionslos
* [x] Raumname fehlt in der ersten Spalte vor den Zeilen

## Checklisten

- [x] Abgehakte ToDos sichtbar machen. Sind nicht wieder auffindbar, wenn einmal abgehakt, außer man weiß noch in welchem Projekt es war.
- [x] Tasks ohne Zuordnung werden automatisch zugeordnet, why?
- [x] Abhaken auf dem Dashboard funktioniert nicht.

## Teams

- [x] Icon nicht änderbar

## Users

* [x] User können nicht angelegt werden, 500er (evtl. wegen Mailer Error?)
* [x] User laden nicht/sehr langsam, wenn Abwesenheiten eingetragen (7800 aus Kulturklick importiert)

## Papierkorb

- [x] gelöschte Räume sind nicht sichtbar
- [x] 500er beim Versuch, gelöschte Area entgültig zu löschen

**Comment by guischdi** [comment]
[ ] in Firefox gehen diverse Links nicht (z.B. in Projekten weitere Reiter oder Nutzer*innen > User > alle Tabs außer dem ersten, sehr doof wenn man Rechte vergeben will). Wurde wohl nur mit Chrome getestet.

**Comment by Muelle96** [comment]
Wir haben dies sowohl bei der Entwicklung als auch jetzt mit sämtlichen Browsern getestet und haben keine Probleme feststellen können. Ich denke ein Update auf den neuesten Stand des Main-Branches mit Cache clear behebt das Problem. Zudem bitte ich um professionelle Kommunikation ohne Suggestionen oder "face_palm".
