### ISSUE TITLE
Fehler 500 beim Einladen von Nutzer*innen

### ISSUE THREAD

**Issue by NoelPeiris** [artwork-software/artwork#729]
Hallo!
habe über die Update Routine alles auf den neuesten Stand gebracht und bekommen beim Einladen von neuen Personen einen Fehler 500 angezeigt. Dies passierte auch vor dem Update.

Gibts dafür eine Lösung und braucht ihr eine Log Datei?

Habe SSL eingerichtet und in der .env strato als smpt angegeben. 

SOKETI_SSL_CERT=/etc/letsencrypt/live/dockartwork.de/fullchain.pem
SOKETI_SSL_KEY=/etc/letsencrypt/live/dockartwork.de/privkey.pem
SOKETI_SSL_CA= # Optional, wenn eine CA verwendet wird
SOKETI_SSL_PASS= # Optional, wenn ein Passwort für den Schlüssel benötigt wird

habe ich ebenfalls eingefügt

Alle anderen Menüs scheinen zu funktionieren.

Vielen Dank und gute Nacht!

**Comment by Muelle96** [comment]
Hi Noel,

mehrere Häuser hatten bisher das Problem, dass die eigene Firewall die Mails nicht rausschicken wollte, da die Absender-Email nicht freigegeben wurde, eventuell ist das hier auch das Problem. Die Absender-Email ist mittlerweile frei einstellbar unter Einstellungen -> Tool -> Tab "Kommunikation & Rechtliches" -> Einladungs-E-Mail-Adresse, sollte dort nichts eingetragen sein, wird standardmäßig die "SYSTEM_MAIL" aus der env file genutzt, wenn unverändert ist dies "noreply@artwork.software. 

Sollte dies das Problem nicht fixen, sende uns gerne die Log-Datei oder die passende Fehlermeldung aus der Log-Datei, damit wir da mehr Nachforschen können. 

Beste Grüße!

**Comment by NoelPeiris** [comment]
Hallo nochmal, 

konnte das Problem "lösen". Hab es mit anderen Anbietern ausprobiert und die Logdatei zeigte immer Authentifizierungsfehler an. Erst als ich das Passwort vereinfacht habe, lief es dann. Rausgenommen habe ich die Sonderzeichen "#" und "-" und das Passwort besteht jetzt aus vielen Groß- und Kleinbuchstaben, sowie Zahlen. 
Könnte das ein Codierungsfehler sein, dass das Passwort nicht richtig überträgt?

Viele Grüße
Noel

**Comment by Muelle96** [comment]
Hi Noel, 

die Raute in der .env file sagt an, dass ein Komemntar folgt, wenn du das Passwort nicht in Anführungszeichen gesetzt hast. Demnach hättest du es dann so dort reinschreiben müssen: PASSWORD="HIER DEIN PASSWORT". Durch die Schreibweise ohne Anführungszeichen hast du Recht,dass die # dann das Passwort nicht richtig übertragen hat. 

Beste Grüße 

Jannik
