### ISSUE TITLE
question limited characters in project information tab

### ISSUE THREAD

**Issue by FabianStemmer** [artwork-software/artwork#755]
Hi, 

I have a quick question about the “Project Information” tab. When I enter something under “Short Description” or “Website Text”, it is somehow limited to only 255 characters, which indicates the byte data type, but the database contains json, which can theoretically be much larger. Is this intentional or an unintentional bug?

Best regards,
Fabian

**Comment by Muelle96** [comment]
Hi Fabian,

until now this was limited by the frontend, for all text areas we set the limit up to 2000 characters now. The next update will bring this change, thanks for finding this unneeded limit. 

Best regards,
Jannik
