### ISSUE TITLE
timeissue in pdf calendar export

### ISSUE THREAD

**Issue by FabianStemmer** [artwork-software/artwork#777]
Hi there,

I don't know if Ben already told you about this little bug in the pdf export function of the calendar. Obviously, the times for the events are printed in UTC server time, while the actual entered times are displayed with local server time. Is this intensional? If yes I'd need to change all my import data from previous events (which isn't a problem at all but would be good to know).

My best,
Fabian

![artwork_zeit](https://github.com/user-attachments/assets/6664e565-d6c6-40b2-94b9-bb662a6b7df9)

**Comment by timodeeken** [comment]
Hi Fabian, we have already fixed the bug on the ‘Dev’ branch. The time in the export is now based on the time zone specified in the configuration.
